version: "2.4"

services:

    database:
        container_name: database
        image: registry.heroku.com/hk-mongoose/kbs_database
        restart: "no"
        ports:
            - '5432:5432'
        environment:
            # Container run-time arguments
            # You should already have run previously: source .env
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    mongoose:
        depends_on:
            - database
        container_name: mongoose
        image: mongoose-with-db
        restart: "no"
        ports:
            - '80:80'
            - '9090:9090'
        command:  java -jar mongoose-base-server-application-vertx-1.0.0-SNAPSHOT-fat.jar

    web:
        depends_on:
            - mongoose
        container_name: mongoose-web
        image: mongoose-web
        restart: "no"
        ports:
            - '8082:8080'
